#!/usr/bin/env python
import os
import sys

import toml
from it.base import Tool
from it.core import load_tools, tool_list_exists

if __name__ == '__main__':
    available_tools = toml.load("pennywise.toml")
    cmd = sys.argv[1]

    if not tool_list_exists():
        load_tools()

    if cmd == "list":
        for tool, value in available_tools.items():
            help_text = value.get("help", "No help provided")
            print(f"{tool} - {help_text}")

        sys.exit(0)

    elif cmd == "install":
        print("Install specific tool")

    elif cmd == "source":
        load_tools()

    elif cmd in available_tools.keys():
        current_dir = os.getcwd()
        image = available_tools[cmd]["image"]
        prefix_cmd = available_tools[cmd]["prefix_cmd"]

        tool = Tool(image, prefix_cmd)
        tool.run(sys.argv[2:], current_dir)

    else:
        print("Pennywise can't change into this tool.")
